### ISSUE TITLE
crashes after opening 

### ISSUE THREAD

**Issue by doy** [niftynei/HSFacesAndroid#22] opened 2015-06-10 20:01 UTC
After the latest update, the app loads and works fine for a few seconds, then crashes.

**Comment by niftynei** [comment] 2015-06-10 20:33
Thanks for the report @doy!  I got an email about this crash earlier today, that's probably the crash you're experiencing.

````
java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.google.android.gms.analytics.service.START (has extras) }
       at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1680)
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1779)
       at android.app.ContextImpl.bindService(ContextImpl.java:1757)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:539)
````

If you're curious, it seems to be caused by an out of date Google Analytics library. Link to SO post [here.](http://stackoverflow.com/a/26554858)

**Comment by niftynei** [comment] 2015-07-03 21:31
I released a new version of the app today that includes the newest version of google analytics.  I wasn't able to reliably reproduce the bug, but this should fix the error. Please let me know if not.

Closing this issue for now though. Thanks for the report!

**Closed by niftynei** 2015-07-03 21:31 UTC
